export const IPC_CHANNELS = {
  sftpConnect: "sftp:connectForTab",
  sftpDisconnect: "sftp:disconnectForTab",
  sftpListDirectory: "sftp:listDirectoryForTab",
  sftpDelete: "sftp:deleteForTab",
  localDelete: "local:delete",
  tabDispose: "tab:dispose",
  terminalStart: "terminal:start",
  terminalWrite: "terminal:write",
  terminalResize: "terminal:resize",
  terminalClose: "terminal:close",
  terminalData: "terminal:data",
  terminalClosed: "terminal:closed",
  fileReadLocal: "file:readLocal",
  fileWriteLocal: "file:writeLocal",
  fileReadRemote: "file:readRemote",
  fileWriteRemote: "file:writeRemote",
  transferEnqueue: "transfer:enqueue",
  transferProgress: "transfer:progress",
  compareDirectories: "compare:directories",
  walkLocalDirectory: "local:walkDirectory",
  walkRemoteDirectory: "sftp:walkDirectory",
  sessionList: "session:list",
  sessionSave: "session:save",
  sessionDelete: "session:delete",
  watchStart: "watch:start",
  watchStop: "watch:stop",
} as const;
